n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'CE'

plm_suffix: blair-roberta-base.feature
plm_size: 768
adaptor_dropout_prob: 0.2
adaptor_layers: [768,300,64]
